package com.ypy.model;

import java.math.BigDecimal;

public class UserModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YONG.T_USER.USERID
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YONG.T_USER.USERNAME
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YONG.T_USER.PASSWORD
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YONG.T_USER.AGE
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    private Short age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YONG.T_USER.DID
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    private BigDecimal did;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YONG.T_USER.USERID
     *
     * @return the value of YONG.T_USER.USERID
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YONG.T_USER.USERID
     *
     * @param userid the value for YONG.T_USER.USERID
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YONG.T_USER.USERNAME
     *
     * @return the value of YONG.T_USER.USERNAME
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YONG.T_USER.USERNAME
     *
     * @param username the value for YONG.T_USER.USERNAME
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YONG.T_USER.PASSWORD
     *
     * @return the value of YONG.T_USER.PASSWORD
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YONG.T_USER.PASSWORD
     *
     * @param password the value for YONG.T_USER.PASSWORD
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YONG.T_USER.AGE
     *
     * @return the value of YONG.T_USER.AGE
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YONG.T_USER.AGE
     *
     * @param age the value for YONG.T_USER.AGE
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YONG.T_USER.DID
     *
     * @return the value of YONG.T_USER.DID
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    public BigDecimal getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YONG.T_USER.DID
     *
     * @param did the value for YONG.T_USER.DID
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    public void setDid(BigDecimal did) {
        this.did = did;
    }
}