package com.ypy.dao;

import java.util.List;

import com.ypy.model.UserModel;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YONG.T_USER
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YONG.T_USER
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YONG.T_USER
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YONG.T_USER
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    UserModel selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YONG.T_USER
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YONG.T_USER
     *
     * @mbggenerated Tue Oct 24 16:22:40 CST 2017
     */
    int updateByPrimaryKey(UserModel record);
    
    /**
     * 按条件查询数据
     * @param user
     * @return
     */
    List<UserModel> querySelective(UserModel user);
}